import type { Metadata } from "next";
import { Inter, Lato, Sora } from "next/font/google";
import "./globals.css";
import ScrollProvider from "@/components/ScrollProvider/ScrollProvider";

const inter = Inter({ subsets: ["latin"] });
const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Framer Motion ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <ScrollProvider>{children}</ScrollProvider>
      </body>
    </html>
  );
}
