import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/applayout/Header";
import Navbar from "@/components/applayout/Navbar";
import Footer from "@/components/applayout/Footer";
import { Cinzel, Lato, Manrope, Open_Sans, Montserrat } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "New Aitc",
  description: "Generated by create next app",
};
const lato = Lato({
  weight: ["400", "700", "900", "300", "100",],
  subsets: ["latin", "latin-ext"],
  variable: "--font-lato",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} bg-white font-lato `}>
        <Header />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
