import type { Metadata } from "next";
import { Inter, Sora } from "next/font/google";
import "./globals.css";
import ScrollProvider from "@/components/ScrollProvider/ScrollProvider";

import localFont from "next/font/local";

// Define your local font
const greycliff = localFont({
  src: [
    {
      path: "../public/fonts/greycliffcf/regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/greycliffcf/bold.woff2",
      weight: "700",
      style: "normal",
    },
    // Add other weights and styles as needed
  ],
  variable: "--font-greycliff", // This creates a CSS variable
});

const inter = Inter({ subsets: ["latin"] });
const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Animation Playground",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={greycliff.className}>
        <ScrollProvider>{children}</ScrollProvider>
      </body>
    </html>
  );
}
